---
title: Facing Life
description: Eight people reentering society after serving life sentences in California
  prisons. Created by Pendarvis Harshaw and Brandon Tauszik.
url: https://facing-life.testing.sutty.nl
hostname: facing-life.testing.sutty.nl
locales:
- es
- en
