name: "Distributed Press"
on:
  push:
    branches:
    - "main"
jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Publish to Distributed Press"
      uses: "hyphacoop/actions-distributed-press@v1.1"
      with:
        publish_dir: "."
        dp_url: "https://api.distributed.press"
        refresh_token: "${{ secrets.REFRESH_TOKEN }}"
        site_url: "facing.life"
